# Generated by Django 6.0.6 on 2026-06-19 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arise', '0002_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
