# Generated by Django 6.0.6 on 2026-06-20 18:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arise', '0004_passwordresetotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('Email', models.EmailField(blank=True, max_length=255, null=True)),
                ('Date', models.DateField(blank=True, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Amount', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Updated_at', models.DateTimeField(auto_now=True)),
                ('CSD', models.ForeignKey(blank=True, db_column='CSD', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_communities', to='Arise.staff')),
                ('Headmaster', models.ForeignKey(blank=True, db_column='Headmaster', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_communities', to='Arise.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('Email', models.EmailField(blank=True, max_length=255, null=True)),
                ('Phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('Sponsor_number', models.CharField(blank=True, max_length=100, null=True)),
                ('Address_line_1', models.TextField(blank=True, null=True)),
                ('Address_line_2', models.TextField(blank=True, null=True)),
                ('Country', models.CharField(blank=True, max_length=100, null=True)),
                ('State', models.CharField(blank=True, max_length=100, null=True)),
                ('City', models.CharField(blank=True, max_length=100, null=True)),
                ('Zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('User', models.ForeignKey(blank=True, db_column='User', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Student_number', models.IntegerField(blank=True, null=True, unique=True)),
                ('Full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('Date_of_birth', models.CharField(blank=True, max_length=100, null=True)),
                ('Gender', models.CharField(blank=True, max_length=10, null=True)),
                ('Current_grade', models.IntegerField(blank=True, null=True)),
                ('Enrollment_term', models.CharField(blank=True, max_length=100, null=True)),
                ('Profile_photo', models.ImageField(blank=True, null=True, upload_to='student_photos/')),
                ('Headshot', models.ImageField(blank=True, null=True, upload_to='student_headshots/')),
                ('Bio', models.TextField(blank=True, null=True)),
                ('Is_sponsored', models.BooleanField(default=False)),
                ('Fee_paying', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('CSO_id', models.ForeignKey(blank=True, db_column='CSO_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cso_students', to='Arise.staff')),
                ('Community_id', models.ForeignKey(blank=True, db_column='Community_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='Arise.community')),
                ('Sponsor_id', models.ForeignKey(blank=True, db_column='Sponsor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsored_students', to='Arise.sponsor')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsorship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Payment_type', models.CharField(blank=True, max_length=100, null=True)),
                ('Date', models.DateField(blank=True, null=True)),
                ('Due_date', models.DateField(blank=True, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Amount', models.CharField(blank=True, max_length=100, null=True)),
                ('Status', models.CharField(blank=True, max_length=100, null=True)),
                ('Sponsor_id', models.ForeignKey(db_column='Sponsor_id', on_delete=django.db.models.deletion.CASCADE, related_name='sponsorships', to='Arise.sponsor')),
                ('Student_id', models.ForeignKey(db_column='Student_id', on_delete=django.db.models.deletion.CASCADE, related_name='sponsorships', to='Arise.student')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Content', models.TextField(blank=True, null=True)),
                ('Prayer_request', models.TextField(blank=True, null=True)),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='report_photos/')),
                ('Report_term', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('date_submitted', models.DateField(blank=True, null=True)),
                ('is_Zambian_approved', models.BooleanField(default=False)),
                ('is_american_approved', models.BooleanField(default=False)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Updated_at', models.DateTimeField(auto_now=True)),
                ('American_approver', models.ForeignKey(blank=True, db_column='American_approver', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='american_approved_reports', to='Arise.staff')),
                ('CSD', models.ForeignKey(blank=True, db_column='CSD', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='csd_reports', to='Arise.staff')),
                ('CSO', models.ForeignKey(blank=True, db_column='CSO', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cso_reports', to='Arise.staff')),
                ('Student', models.ForeignKey(db_column='Student', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='Arise.student')),
            ],
        ),
        migrations.CreateModel(
            name='HealthConditions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Condition_name', models.CharField(blank=True, max_length=255, null=True)),
                ('Condition_description', models.TextField(blank=True, null=True)),
                ('Condition_status', models.CharField(blank=True, max_length=100, null=True)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Updated_at', models.DateTimeField(auto_now=True)),
                ('Student', models.ForeignKey(db_column='Student', on_delete=django.db.models.deletion.CASCADE, related_name='health_conditions', to='Arise.student')),
            ],
        ),
        migrations.CreateModel(
            name='GuardianInformation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Guardian_name', models.CharField(blank=True, max_length=255, null=True)),
                ('Guardian_phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('Guardian_NRC', models.CharField(blank=True, max_length=100, null=True)),
                ('Primary_caretaker', models.CharField(blank=True, max_length=255, null=True)),
                ('Caretaker_occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('Highest_education', models.CharField(blank=True, max_length=255, null=True)),
                ('Can_read', models.BooleanField(default=False)),
                ('Guardian_comments', models.TextField(blank=True, null=True)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(db_column='student', on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='Arise.student')),
            ],
        ),
        migrations.CreateModel(
            name='DemographicHealthDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Living_parents', models.CharField(blank=True, max_length=255, null=True)),
                ('Mother_relationship', models.CharField(blank=True, max_length=255, null=True)),
                ('Father_relationship', models.CharField(blank=True, max_length=255, null=True)),
                ('Siblings', models.IntegerField(blank=True, null=True)),
                ('Distance_to_school', models.IntegerField(blank=True, null=True)),
                ('Meals_per_week', models.IntegerField(blank=True, null=True)),
                ('People_in_the_house', models.IntegerField(blank=True, null=True)),
                ('People_in_school', models.IntegerField(blank=True, null=True)),
                ('Reliable_income', models.IntegerField(blank=True, null=True)),
                ('can_read', models.IntegerField(blank=True, null=True)),
                ('Has_vehicle', models.BooleanField(default=False)),
                ('Has_electricity', models.BooleanField(default=False)),
                ('Has_water', models.BooleanField(default=False)),
                ('Distance_to_water', models.IntegerField(blank=True, null=True)),
                ('HIV_status', models.BooleanField(default=False)),
                ('Has_disability', models.BooleanField(default=False)),
                ('Demographic_comments', models.TextField(blank=True, null=True)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Updated_at', models.DateTimeField(auto_now=True)),
                ('Student', models.ForeignKey(db_column='Student', on_delete=django.db.models.deletion.CASCADE, related_name='demographics', to='Arise.student')),
            ],
        ),
    ]
