# Generated by Django 6.0.6 on 2026-06-21 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arise', '0006_story'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorSignUpOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('otp', models.CharField(max_length=5)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='sponsor',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='sponsor_photos/'),
        ),
    ]
