# Generated by Django 6.0.6 on 2026-06-21 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arise', '0007_sponsorsignupotp_sponsor_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='staff',
            field=models.ForeignKey(blank=True, db_column='staff', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsors', to='Arise.staff'),
        ),
    ]
