# Generated by Django 6.0.6 on 2026-06-21 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arise', '0008_sponsor_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Enrollment_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
