# Generated by Django 6.0.6 on 2026-06-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arise', '0009_student_enrollment_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='Photo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='profile_photo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='profile_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Headshot',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Profile_photo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
