# Generated by Django 6.0.6 on 2026-06-23 19:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arise', '0010_alter_report_photo_alter_sponsor_profile_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('grade', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('mt1', models.IntegerField(blank=True, null=True)),
                ('et1', models.IntegerField(blank=True, null=True)),
                ('mt2', models.IntegerField(blank=True, null=True)),
                ('et2', models.IntegerField(blank=True, null=True)),
                ('mt3', models.IntegerField(blank=True, null=True)),
                ('et3', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_records', to='Arise.student')),
            ],
            options={
                'unique_together': {('student', 'year', 'grade', 'subject')},
            },
        ),
    ]
