# Generated by Django 6.0.6 on 2026-06-23 20:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arise', '0011_academicrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('grade', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('week_number', models.IntegerField()),
                ('objectives', models.TextField()),
                ('materials', models.TextField(blank=True, null=True)),
                ('procedures', models.TextField()),
                ('assessment', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Draft', max_length=50)),
                ('headmaster_comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='Arise.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='Arise.staff')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_ending_date', models.DateField()),
                ('social_events', models.TextField(blank=True, null=True)),
                ('behavioral_issues', models.TextField(blank=True, null=True)),
                ('health_issues', models.TextField(blank=True, null=True)),
                ('absenteeism', models.TextField(blank=True, null=True)),
                ('other_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports', to='Arise.staff')),
            ],
            options={
                'unique_together': {('teacher', 'week_ending_date')},
            },
        ),
    ]
