# Generated by Django 6.0.6 on 2026-06-23 20:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arise', '0012_lessonplan_notification_weeklyreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='american_editor',
            field=models.ForeignKey(blank=True, db_column='american_editor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='american_edited_reports', to='Arise.staff'),
        ),
        migrations.CreateModel(
            name='ReportComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_comments', to='Arise.staff')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Arise.report')),
            ],
        ),
    ]
